name: Run tests
on:
  push:
    paths:
      - "public/**"
      - "src/**"
      - "test/**"
  pull_request:
    paths:
      - "public/**"
      - "src/**"
      - "test/**"
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15
          
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run : npm run test

      - name: Check for circular dependencies using Madge
        uses: gerrit0/circular-dependency-check@v1
        with:
          entry: >
            src/index.ts
          extensions: >
            ts

      - name: Upload coverage info to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
